# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatResult',
            fields=[
                ('catcode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('batseats', models.IntegerField(default=1)),
                ('batcount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Batters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batseat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.BatResult')),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_title', models.CharField(max_length=30)),
                ('is_finished', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='CupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=2)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Cup')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playdate', models.DateField()),
                ('guest_score', models.IntegerField(default=0)),
                ('home_score', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False, verbose_name='')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Cup')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlayPosition',
            fields=[
                ('position', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Team'),
        ),
        migrations.AddField(
            model_name='cupgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Team'),
        ),
        migrations.AddField(
            model_name='batters',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='batters',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Member'),
        ),
        migrations.AddField(
            model_name='batters',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.PlayPosition'),
        ),
        migrations.AddField(
            model_name='batters',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Team'),
        ),
    ]
