# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batters',
            name='position',
            field=models.CharField(choices=[('1', 'P'), ('2', 'C'), ('3', '1B'), ('4', '2B'), ('5', '3B'), ('6', 'SS'), ('7', 'LF'), ('8', 'CF'), ('9', 'RF'), ('DH', 'DH')], max_length=2),
        ),
    ]
