# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180307_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cup',
        ),
        migrations.RemoveField(
            model_name='game',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='game',
            name='playdate',
        ),
        migrations.AddField(
            model_name='game',
            name='schedule',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='games.Schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='cup',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='games.Cup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='dif_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='playdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
