# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_member_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupgroup',
            name='cup',
        ),
        migrations.RemoveField(
            model_name='cupgroup',
            name='team',
        ),
        migrations.DeleteModel(
            name='CupGroup',
        ),
    ]
