# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20180307_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=2)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Cup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Team')),
            ],
        ),
    ]
