# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20180307_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayPosition',
        ),
    ]
