# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_delete_playposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='home',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='games.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.Team'),
        ),
    ]
