# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20180307_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('cup', 'guest', 'home')]),
        ),
    ]
