# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_remove_batters_batseat1'),
    ]

    operations = [
        migrations.AddField(
            model_name='batters',
            name='batseat1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat1', to='games.BatResult'),
        ),
        migrations.AddField(
            model_name='batters',
            name='batseat2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat2', to='games.BatResult'),
        ),
        migrations.AddField(
            model_name='batters',
            name='batseat3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat3', to='games.BatResult'),
        ),
        migrations.AddField(
            model_name='batters',
            name='batseat4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat4', to='games.BatResult'),
        ),
        migrations.AddField(
            model_name='batters',
            name='batseat5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat5', to='games.BatResult'),
        ),
        migrations.AddField(
            model_name='batters',
            name='batseat6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batseat6', to='games.BatResult'),
        ),
    ]
