# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20180308_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batters',
            name='game',
        ),
        migrations.AddField(
            model_name='batters',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.Schedule'),
            preserve_default=False,
        ),
    ]
