# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20180308_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batters',
            new_name='BatterOrder',
        ),
    ]
