# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20180308_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.Schedule'),
        ),
    ]
