# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_remove_batterorder_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterorder',
            name='batseat6',
        ),
    ]
