# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20180308_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='季賽結束'),
        ),
    ]
