# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_batterorder_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterorder',
            name='game',
        ),
    ]
