# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20180309_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='guest_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_score',
        ),
        migrations.AddField(
            model_name='schedule',
            name='guest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
