# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_batterorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterorder',
            name='schedule',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='games.Schedule'),
            preserve_default=False,
        ),
    ]
