# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_auto_20180313_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
    ]
