# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_batterorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterorder',
            old_name='gameschedule',
            new_name='schedule',
        ),
    ]
