# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_auto_20180313_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
